import {
  Battery,
  Bell,
  Briefcase,
  Cable,
  Calculator,
  Camera,
  Cpu,
  Droplets,
  Fan,
  Gamepad2,
  HardDrive,
  Headphones,
  House,
  Keyboard,
  Laptop,
  LayoutGrid,
  Lock,
  MemoryStick,
  Mic,
  Monitor,
  Mouse,
  Network,
  Package,
  Phone,
  Plug,
  Printer,
  Projector,
  ScanLine,
  Server,
  Smartphone,
  Speaker,
  Tablet,
  Tv,
  Watch,
  Wifi,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  grid: LayoutGrid,
  laptop: Laptop,
  monitor: Monitor,
  cpu: Cpu,
  memory: MemoryStick,
  box: Package,
  fan: Fan,
  plug: Plug,
  keyboard: Keyboard,
  mouse: Mouse,
  headphones: Headphones,
  camera: Camera,
  printer: Printer,
  scan: ScanLine,
  droplet: Droplets,
  network: Network,
  wifi: Wifi,
  server: Server,
  phone: Phone,
  battery: Battery,
  cable: Cable,
  "hard-drive": HardDrive,
  smartphone: Smartphone,
  tablet: Tablet,
  speaker: Speaker,
  mic: Mic,
  tv: Tv,
  projector: Projector,
  gamepad: Gamepad2,
  cctv: Camera,
  lock: Lock,
  bell: Bell,
  pos: Calculator,
  briefcase: Briefcase,
  calculator: Calculator,
  app: LayoutGrid,
  home: House,
  watch: Watch,
};

export function catalogIcon(name: string) {
  return ICONS[name] ?? LayoutGrid;
}
